"""Refill alert model — proactive predictions from Agent 3."""

import uuid
from datetime import datetime

from sqlalchemy import String, Float, DateTime, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.compat import DBUUID


class RefillAlert(Base):
    """Proactive refill alert generated by the Predictive Agent."""

    __tablename__ = "refill_alerts"

    alert_id: Mapped[uuid.UUID] = mapped_column(
        DBUUID, primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        DBUUID, ForeignKey("users.user_id", ondelete="CASCADE"), index=True
    )
    medicine_id: Mapped[uuid.UUID] = mapped_column(
        DBUUID, ForeignKey("medicines.medicine_id", ondelete="CASCADE")
    )

    alert_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    estimated_run_out: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    status: Mapped[str] = mapped_column(String(50), default="pending")

    # Relationships
    user: Mapped["User"] = relationship()  # noqa: F821
    medicine: Mapped["Medicine"] = relationship()  # noqa: F821
